project:
  type: website
  output-dir: docs

website:
  title: "Data Science, Analytics and ML"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Blog

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



